### PR TITLE
Remove /test

### PR DESCRIPTION
**Pull request by adarsh**
# Reason for Change
- We switched over to RSpec in 4de1b569381bfc6b83337774bbb20f2c645039aa but looks like forgot to delete the `/test` directory.
- Whoops!
# Changes
- `rm -rf test/`

### CODE REVIEW

**Comment by alieander** [comment]
This is probably be fine if we are going to remove the RakeTask anyway.

**Comment by adarsh** [comment]
Cool. I will hold on this until we remove the Raketask stuff.

**Comment by adarsh** [comment]
Opened the Raketask removal stuff in https://github.com/fastly/fastly_nsq/pull/18. 

When that one is merged, this one is okay to merge.

**Comment by alieander** [comment]
https://github.com/fastly/fastly_nsq/pull/19
This should cover this.

**Pull request closed without merging**
